// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Article documents */
interface ArticleDocumentData {
  /**
   * Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Author Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.author_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  author_image: prismicT.ImageField<never>;
  /**
   * Author Name field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.author_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  author_name: prismicT.KeyTextField;
  /**
   * Date field in *Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  date: prismicT.DateField;
  /**
   * Cover Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  cover_image: prismicT.ImageField<never>;
  /**
   * Article Content field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.article_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  article_content: prismicT.RichTextField;
  /**
   * Bio field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  bio: prismicT.KeyTextField;
}
/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;
/** Content for Blog documents */
interface BlogDocumentData {
  /**
   * Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
}
/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<Simplify<BlogDocumentData>, "blog", Lang>;
/** Content for Cookie documents */
interface CookieDocumentData {
  /**
   * Title field in *Cookie*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description Up field in *Cookie*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.description_up
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description_up: prismicT.RichTextField;
  /**
   * Description Down field in *Cookie*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.description_down
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description_down: prismicT.RichTextField;
  /**
   * Card field in *Cookie*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  card: prismicT.GroupField<Simplify<CookieDocumentDataCardItem>>;
}
/**
 * Item in Cookie → Card
 *
 */
export interface CookieDocumentDataCardItem {
  /**
   * Description field in *Cookie → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.card[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Title Left field in *Cookie → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.card[].title_left
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_left: prismicT.KeyTextField;
  /**
   * Description Left field in *Cookie → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.card[].description_left
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description_left: prismicT.KeyTextField;
  /**
   * Title Right field in *Cookie → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.card[].title_right
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_right: prismicT.KeyTextField;
  /**
   * Description Right field in *Cookie → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.card[].description_right
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description_right: prismicT.KeyTextField;
}
/**
 * Cookie document from Prismic
 *
 * - **API ID**: `cookie`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CookieDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<CookieDocumentData>,
    "cookie",
    Lang
  >;
/** Content for Footer documents */
interface FooterDocumentData {
  /**
   * Link List field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.link_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  link_list: prismicT.GroupField<Simplify<FooterDocumentDataLinkListItem>>;
  /**
   * Tip field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.tip
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  tip: prismicT.KeyTextField;
  /**
   * Title Success field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title_success
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_success: prismicT.KeyTextField;
  /**
   * Title Fail field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title_fail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_fail: prismicT.KeyTextField;
  /**
   * Button Label field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.button_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_label: prismicT.KeyTextField;
  /**
   * Button Placeholder field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.button_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_placeholder: prismicT.KeyTextField;
  /**
   * Column Left field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_left
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  column_left: prismicT.KeyTextField;
  /**
   * Column Middle First field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_middle_first
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  column_middle_first: prismicT.KeyTextField;
  /**
   * Column Middle Second field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_middle_second
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  column_middle_second: prismicT.KeyTextField;
  /**
   * Column Right field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.column_right
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  column_right: prismicT.KeyTextField;
}
/**
 * Item in Footer → Link List
 *
 */
export interface FooterDocumentDataLinkListItem {
  /**
   * Label field in *Footer → Link List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.link_list[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField;
  /**
   * Link field in *Footer → Link List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.link_list[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  link: prismicT.KeyTextField;
}
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;
/** Content for GDPR documents */
interface GdprDocumentData {
  /**
   * Title field in *GDPR*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gdpr.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *GDPR*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gdpr.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * GDPR document from Prismic
 *
 * - **API ID**: `gdpr`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GdprDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<Simplify<GdprDocumentData>, "gdpr", Lang>;
/** Content for Header documents */
interface HeaderDocumentData {
  /**
   * Link List field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  link_list: prismicT.GroupField<Simplify<HeaderDocumentDataLinkListItem>>;
  /**
   * Button Icon Classname field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.button_icon_classname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_icon_classname: prismicT.KeyTextField;
  /**
   * Button Label field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.button_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_label: prismicT.KeyTextField;
  /**
   * Button Link field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_link: prismicT.KeyTextField;
}
/**
 * Item in Header → Link List
 *
 */
export interface HeaderDocumentDataLinkListItem {
  /**
   * Link field in *Header → Link List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_list[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  link: prismicT.KeyTextField;
  /**
   * Label field in *Header → Link List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_list[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField;
}
/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;
/** Content for Page documents */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice =
  | BannerSlice
  | ComparisonTablesSlice
  | FaqSlice
  | FeaturesSlice
  | HeroSlice
  | HighlightSlice
  | PricingSlice
  | ProcessSlice
  | HighlightNormalSlice
  | ReveiwsSlice
  | RewardSlice
  | TestimonialsSlice
  | TwoColumnsSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Pricing documents */
interface PricingDocumentData {
  /**
   * Title field in *Pricing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Pricing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
  /**
   * Slice Zone field in *Pricing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<PricingDocumentDataSlicesSlice>;
}
/**
 * Slice for *Pricing → Slice Zone*
 *
 */
type PricingDocumentDataSlicesSlice =
  | PricingSlice
  | HighlightSlice
  | FeaturesSlice
  | FaqSlice;
/**
 * Pricing document from Prismic
 *
 * - **API ID**: `pricing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PricingDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<PricingDocumentData>,
    "pricing",
    Lang
  >;
/** Content for Privacy documents */
interface PrivacyDocumentData {
  /**
   * Title field in *Privacy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Privacy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Privacy document from Prismic
 *
 * - **API ID**: `privacy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<PrivacyDocumentData>,
    "privacy",
    Lang
  >;
export type AllDocumentTypes =
  | ArticleDocument
  | BlogDocument
  | CookieDocument
  | FooterDocument
  | GdprDocument
  | HeaderDocument
  | PageDocument
  | PricingDocument
  | PrivacyDocument;
/**
 * Primary content in Banner → Primary
 *
 */
interface BannerSliceDefaultPrimary {
  /**
   * Title field in *Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
}
/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Banner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Banner*
 *
 */
type BannerSliceVariation = BannerSliceDefault;
/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: `Banner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSlice = prismicT.SharedSlice<"banner", BannerSliceVariation>;
/**
 * Primary content in ComparisonTables → Primary
 *
 */
interface ComparisonTablesSliceDefaultPrimary {
  /**
   * Highlight Title field in *ComparisonTables → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_tables.primary.highlight_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  highlight_title: prismicT.KeyTextField;
  /**
   * Title field in *ComparisonTables → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_tables.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * SubTitle Left field in *ComparisonTables → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_tables.primary.subtitle_left
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle_left: prismicT.KeyTextField;
  /**
   * SubDescription Left field in *ComparisonTables → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_tables.primary.subdescription_left
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subdescription_left: prismicT.KeyTextField;
  /**
   * SubTitle Right field in *ComparisonTables → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_tables.primary.subtitle_right
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle_right: prismicT.KeyTextField;
  /**
   * Description Right field in *ComparisonTables → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_tables.primary.description_right
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description_right: prismicT.KeyTextField;
}
/**
 * Item in ComparisonTables → Items
 *
 */
export interface ComparisonTablesSliceDefaultItem {
  /**
   * Title field in *ComparisonTables → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_tables.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Check field in *ComparisonTables → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: comparison_tables.items[].check
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  check: prismicT.BooleanField;
}
/**
 * Default variation for ComparisonTables Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ComparisonTables`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ComparisonTablesSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<ComparisonTablesSliceDefaultPrimary>,
  Simplify<ComparisonTablesSliceDefaultItem>
>;
/**
 * Slice variation for *ComparisonTables*
 *
 */
type ComparisonTablesSliceVariation = ComparisonTablesSliceDefault;
/**
 * ComparisonTables Shared Slice
 *
 * - **API ID**: `comparison_tables`
 * - **Description**: `ComparisonTables`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ComparisonTablesSlice = prismicT.SharedSlice<
  "comparison_tables",
  ComparisonTablesSliceVariation
>;
/**
 * Primary content in Faq → Primary
 *
 */
interface FaqSliceDefaultPrimary {
  /**
   * Title field in *Faq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Faq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
}
/**
 * Item in Faq → Items
 *
 */
export interface FaqSliceDefaultItem {
  /**
   * Title field in *Faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;
/**
 * Primary content in Faq → Primary
 *
 */
interface FaqSliceStyle1Primary {
  /**
   * Title field in *Faq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Faq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
}
/**
 * Item in Faq → Items
 *
 */
export interface FaqSliceStyle1Item {
  /**
   * Title field in *Faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * style1 variation for Faq Slice
 *
 * - **API ID**: `style1`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSliceStyle1 = prismicT.SharedSliceVariation<
  "style1",
  Simplify<FaqSliceStyle1Primary>,
  Simplify<FaqSliceStyle1Item>
>;
/**
 * Slice variation for *Faq*
 *
 */
type FaqSliceVariation = FaqSliceDefault | FaqSliceStyle1;
/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSlice = prismicT.SharedSlice<"faq", FaqSliceVariation>;
/**
 * Primary content in Features → Primary
 *
 */
interface FeaturesSliceDefaultPrimary {
  /**
   * Title field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * ButtonText field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttontext: prismicT.KeyTextField;
}
/**
 * Item in Features → Items
 *
 */
export interface FeaturesSliceDefaultItem {
  /**
   * Title field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
  /**
   * Icon Classname field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_classname: prismicT.KeyTextField;
}
/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Features`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  Simplify<FeaturesSliceDefaultItem>
>;
/**
 * Primary content in Features → Primary
 *
 */
interface FeaturesSliceFunctionsPrimary {
  /**
   * Title field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * SubTitle field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismicT.KeyTextField;
}
/**
 * Item in Features → Items
 *
 */
export interface FeaturesSliceFunctionsItem {
  /**
   * Title field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Icon Classname field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_classname: prismicT.KeyTextField;
}
/**
 * Functions variation for Features Slice
 *
 * - **API ID**: `functions`
 * - **Description**: `Features`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSliceFunctions = prismicT.SharedSliceVariation<
  "functions",
  Simplify<FeaturesSliceFunctionsPrimary>,
  Simplify<FeaturesSliceFunctionsItem>
>;
/**
 * Slice variation for *Features*
 *
 */
type FeaturesSliceVariation = FeaturesSliceDefault | FeaturesSliceFunctions;
/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: `Features`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSlice = prismicT.SharedSlice<
  "features",
  FeaturesSliceVariation
>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * HighlightTitle field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.highlighttitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  highlighttitle: prismicT.KeyTextField;
  /**
   * Description1 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description1
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description1: prismicT.KeyTextField;
  /**
   * Description2 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description2
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description2: prismicT.KeyTextField;
  /**
   * Description3 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description3
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description3: prismicT.KeyTextField;
  /**
   * ButtonText field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttontext: prismicT.KeyTextField;
  /**
   * ButtonPlaceHolder field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonplaceholder
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttonplaceholder: prismicT.KeyTextField;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceStyle1Primary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * ButtonText field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttontext: prismicT.KeyTextField;
  /**
   * ButtonPlaceHolder field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonplaceholder
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  buttonplaceholder: prismicT.KeyTextField;
  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Item Icon Classname field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.item_icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  item_icon_classname: prismicT.KeyTextField;
  /**
   * Item Title1 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.item_title1
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  item_title1: prismicT.KeyTextField;
  /**
   * Item Title2 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.item_title2
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  item_title2: prismicT.KeyTextField;
  /**
   * Item Title3 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.item_title3
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  item_title3: prismicT.KeyTextField;
}
/**
 * Item in Hero → Items
 *
 */
export interface HeroSliceStyle1Item {
  /**
   * Image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Style1 variation for Hero Slice
 *
 * - **API ID**: `style1`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceStyle1 = prismicT.SharedSliceVariation<
  "style1",
  Simplify<HeroSliceStyle1Primary>,
  Simplify<HeroSliceStyle1Item>
>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceStyle2Primary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_label: prismicT.KeyTextField;
  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * SubTitle field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismicT.KeyTextField;
}
/**
 * Item in Hero → Items
 *
 */
export interface HeroSliceStyle2Item {
  /**
   * Image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Style2 variation for Hero Slice
 *
 * - **API ID**: `style2`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceStyle2 = prismicT.SharedSliceVariation<
  "style2",
  Simplify<HeroSliceStyle2Primary>,
  Simplify<HeroSliceStyle2Item>
>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceStyle3Primary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_label: prismicT.KeyTextField;
  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Item in Hero → Items
 *
 */
export interface HeroSliceStyle3Item {
  /**
   * Image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Style3 variation for Hero Slice
 *
 * - **API ID**: `style3`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceStyle3 = prismicT.SharedSliceVariation<
  "style3",
  Simplify<HeroSliceStyle3Primary>,
  Simplify<HeroSliceStyle3Item>
>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceStyle4Primary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * Button Label1 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label1
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_label1: prismicT.KeyTextField;
  /**
   * Button Label2 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label2
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_label2: prismicT.KeyTextField;
  /**
   * Comment field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.comment
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  comment: prismicT.KeyTextField;
  /**
   * SubTitle field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismicT.KeyTextField;
}
/**
 * Item in Hero → Items
 *
 */
export interface HeroSliceStyle4Item {
  /**
   * Image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Style4 variation for Hero Slice
 *
 * - **API ID**: `style4`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceStyle4 = prismicT.SharedSliceVariation<
  "style4",
  Simplify<HeroSliceStyle4Primary>,
  Simplify<HeroSliceStyle4Item>
>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceStyle1
  | HeroSliceStyle2
  | HeroSliceStyle3
  | HeroSliceStyle4;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in Highlight → Primary
 *
 */
interface HighlightSliceDefaultPrimary {
  /**
   * Title field in *Highlight → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Highlight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * with Slice field in *Highlight → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: highlight.primary.with_slice
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  with_slice: prismicT.BooleanField;
}
/**
 * Item in Highlight → Items
 *
 */
export interface HighlightSliceDefaultItem {
  /**
   * Card Title field in *Highlight → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.items[].card_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  card_title: prismicT.KeyTextField;
}
/**
 * Default variation for Highlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Highlight`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HighlightSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<HighlightSliceDefaultPrimary>,
  Simplify<HighlightSliceDefaultItem>
>;
/**
 * Slice variation for *Highlight*
 *
 */
type HighlightSliceVariation = HighlightSliceDefault;
/**
 * Highlight Shared Slice
 *
 * - **API ID**: `highlight`
 * - **Description**: `Highlight`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HighlightSlice = prismicT.SharedSlice<
  "highlight",
  HighlightSliceVariation
>;
/**
 * Primary content in HighlightNormal → Primary
 *
 */
interface HighlightNormalSliceDefaultPrimary {
  /**
   * Title field in *HighlightNormal → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight_normal.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *HighlightNormal → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight_normal.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
  /**
   * Button Text field in *HighlightNormal → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight_normal.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismicT.KeyTextField;
}
/**
 * Default variation for HighlightNormal Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HighlightNormal`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HighlightNormalSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<HighlightNormalSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *HighlightNormal*
 *
 */
type HighlightNormalSliceVariation = HighlightNormalSliceDefault;
/**
 * HighlightNormal Shared Slice
 *
 * - **API ID**: `highlight_normal`
 * - **Description**: `HighlightNormal`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HighlightNormalSlice = prismicT.SharedSlice<
  "highlight_normal",
  HighlightNormalSliceVariation
>;
/**
 * Primary content in Pricing → Primary
 *
 */
interface PricingSliceDefaultPrimary {
  /**
   * Icon Classname field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_classname: prismicT.KeyTextField;
  /**
   * Title field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
  /**
   * Price Number field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.price_number
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  price_number: prismicT.KeyTextField;
  /**
   * Price Text field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.price_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  price_text: prismicT.KeyTextField;
  /**
   * Button Text field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismicT.KeyTextField;
  /**
   * Is Highlighted field in *Pricing → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: pricing.primary.is_highlighted
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_highlighted: prismicT.BooleanField;
  /**
   * Is Popular field in *Pricing → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: pricing.primary.is_popular
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_popular: prismicT.BooleanField;
  /**
   * Aos Delay field in *Pricing → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.aos_delay
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  aos_delay: prismicT.NumberField;
}
/**
 * Item in Pricing → Items
 *
 */
export interface PricingSliceDefaultItem {
  /**
   * Status field in *Pricing → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: pricing.items[].status
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  status: prismicT.BooleanField;
  /**
   * Title field in *Pricing → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Is New field in *Pricing → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: pricing.items[].is_new
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_new: prismicT.BooleanField;
}
/**
 * Default variation for Pricing Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Pricing`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PricingSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<PricingSliceDefaultPrimary>,
  Simplify<PricingSliceDefaultItem>
>;
/**
 * Slice variation for *Pricing*
 *
 */
type PricingSliceVariation = PricingSliceDefault;
/**
 * Pricing Shared Slice
 *
 * - **API ID**: `pricing`
 * - **Description**: `Pricing`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PricingSlice = prismicT.SharedSlice<
  "pricing",
  PricingSliceVariation
>;
/**
 * Primary content in Process → Primary
 *
 */
interface ProcessSliceDefaultPrimary {
  /**
   * Highlight TItle field in *Process → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.primary.highlight_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  highlight_title: prismicT.KeyTextField;
  /**
   * Title field in *Process → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Process → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
  /**
   * Button Text field in *Process → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismicT.KeyTextField;
}
/**
 * Item in Process → Items
 *
 */
export interface ProcessSliceDefaultItem {
  /**
   * Title field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
  /**
   * Icon ClassName field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.items[].icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_classname: prismicT.KeyTextField;
}
/**
 * Default variation for Process Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Process`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProcessSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<ProcessSliceDefaultPrimary>,
  Simplify<ProcessSliceDefaultItem>
>;
/**
 * Slice variation for *Process*
 *
 */
type ProcessSliceVariation = ProcessSliceDefault;
/**
 * Process Shared Slice
 *
 * - **API ID**: `process`
 * - **Description**: `Process`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProcessSlice = prismicT.SharedSlice<
  "process",
  ProcessSliceVariation
>;
/**
 * Primary content in Reveiws → Primary
 *
 */
interface ReveiwsSliceDefaultPrimary {
  /**
   * Title field in *Reveiws → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reveiws.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
}
/**
 * Item in Reveiws → Items
 *
 */
export interface ReveiwsSliceDefaultItem {
  /**
   * Description field in *Reveiws → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reveiws.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Name field in *Reveiws → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reveiws.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Bio field in *Reveiws → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reveiws.items[].bio
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  bio: prismicT.KeyTextField;
  /**
   * avatar field in *Reveiws → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reveiws.items[].avatar
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  avatar: prismicT.ImageField<never>;
}
/**
 * Default variation for Reveiws Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Reveiws`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ReveiwsSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<ReveiwsSliceDefaultPrimary>,
  Simplify<ReveiwsSliceDefaultItem>
>;
/**
 * Primary content in Reveiws → Primary
 *
 */
interface ReveiwsSliceStyle2Primary {
  /**
   * Title field in *Reveiws → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reveiws.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
}
/**
 * Item in Reveiws → Items
 *
 */
export interface ReveiwsSliceStyle2Item {
  /**
   * Description field in *Reveiws → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reveiws.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Name field in *Reveiws → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reveiws.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Bio field in *Reveiws → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reveiws.items[].bio
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  bio: prismicT.KeyTextField;
  /**
   * avatar field in *Reveiws → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reveiws.items[].avatar
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  avatar: prismicT.ImageField<never>;
}
/**
 * style2 variation for Reveiws Slice
 *
 * - **API ID**: `style2`
 * - **Description**: `Reveiws`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ReveiwsSliceStyle2 = prismicT.SharedSliceVariation<
  "style2",
  Simplify<ReveiwsSliceStyle2Primary>,
  Simplify<ReveiwsSliceStyle2Item>
>;
/**
 * Slice variation for *Reveiws*
 *
 */
type ReveiwsSliceVariation = ReveiwsSliceDefault | ReveiwsSliceStyle2;
/**
 * Reveiws Shared Slice
 *
 * - **API ID**: `reveiws`
 * - **Description**: `Reveiws`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ReveiwsSlice = prismicT.SharedSlice<
  "reveiws",
  ReveiwsSliceVariation
>;
/**
 * Primary content in Reward → Primary
 *
 */
interface RewardSliceDefaultPrimary {
  /**
   * Title Highlight field in *Reward → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reward.primary.title_highlight
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_highlight: prismicT.KeyTextField;
  /**
   * Title Common field in *Reward → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reward.primary.title_common
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_common: prismicT.KeyTextField;
  /**
   * Description field in *Reward → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reward.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
  /**
   * Button Label field in *Reward → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reward.primary.button_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_label: prismicT.KeyTextField;
  /**
   * Button Icon Classname field in *Reward → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reward.primary.button_icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_icon_classname: prismicT.KeyTextField;
}
/**
 * Default variation for Reward Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Reward`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RewardSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<RewardSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Reward*
 *
 */
type RewardSliceVariation = RewardSliceDefault;
/**
 * Reward Shared Slice
 *
 * - **API ID**: `reward`
 * - **Description**: `Reward`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RewardSlice = prismicT.SharedSlice<"reward", RewardSliceVariation>;
/**
 * Primary content in Testimonials → Primary
 *
 */
interface TestimonialsSliceDefaultPrimary {
  /**
   * Title First field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.title_first
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_first: prismicT.KeyTextField;
  /**
   * Number field in *Testimonials → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.number
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  number: prismicT.NumberField;
  /**
   * Title Last field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.title_last
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_last: prismicT.KeyTextField;
}
/**
 * Item in Testimonials → Items
 *
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Logo field in *Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].logo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<never>;
}
/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Testimonials`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;
/**
 * Slice variation for *Testimonials*
 *
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;
/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: `Testimonials`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsSlice = prismicT.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;
/**
 * Default variation for TwoColumns Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TwoColumns`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnsSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;
/**
 * Primary content in TwoColumns → Primary
 *
 */
interface TwoColumnsSliceTextWithLogosPrimary {
  /**
   * Icon Classname field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_classname: prismicT.KeyTextField;
  /**
   * Title field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *TwoColumns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Is Revert field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_revert
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_revert: prismicT.BooleanField;
  /**
   * SubDescription field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.subdescription
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subdescription: prismicT.KeyTextField;
  /**
   * HTML Type field in *TwoColumns → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.html_type
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  html_type: prismicT.SelectField<
    "Singleflow" | "Animation" | "Form" | "Two Image1" | "Two Image2"
  >;
  /**
   * Image field in *TwoColumns → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * Is Background Light field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_background_light
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_background_light: prismicT.BooleanField;
}
/**
 * Item in TwoColumns → Items
 *
 */
export interface TwoColumnsSliceTextWithLogosItem {
  /**
   * Logo field in *TwoColumns → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.items[].logo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<never>;
}
/**
 * Text with Logos variation for TwoColumns Slice
 *
 * - **API ID**: `textWithLogos`
 * - **Description**: `TwoColumns`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnsSliceTextWithLogos = prismicT.SharedSliceVariation<
  "textWithLogos",
  Simplify<TwoColumnsSliceTextWithLogosPrimary>,
  Simplify<TwoColumnsSliceTextWithLogosItem>
>;
/**
 * Primary content in TwoColumns → Primary
 *
 */
interface TwoColumnsSliceTextWithChecklistStyle1Primary {
  /**
   * Icon Classname field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_classname: prismicT.KeyTextField;
  /**
   * Title field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *TwoColumns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Item Icon Classname field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.item_icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  item_icon_classname: prismicT.KeyTextField;
  /**
   * Is Revert field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_revert
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_revert: prismicT.BooleanField;
  /**
   * Image field in *TwoColumns → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * HTML Type field in *TwoColumns → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.html_type
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  html_type: prismicT.SelectField<
    "Singleflow" | "Animation" | "Form" | "Two Image1" | "Two Image2"
  >;
  /**
   * Is Background Light field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_background_light
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_background_light: prismicT.BooleanField;
}
/**
 * Item in TwoColumns → Items
 *
 */
export interface TwoColumnsSliceTextWithChecklistStyle1Item {
  /**
   * Title field in *TwoColumns → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
}
/**
 * Text with Checklist style 1 variation for TwoColumns Slice
 *
 * - **API ID**: `textWithChecklistStyle1`
 * - **Description**: `TwoColumns`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnsSliceTextWithChecklistStyle1 =
  prismicT.SharedSliceVariation<
    "textWithChecklistStyle1",
    Simplify<TwoColumnsSliceTextWithChecklistStyle1Primary>,
    Simplify<TwoColumnsSliceTextWithChecklistStyle1Item>
  >;
/**
 * Primary content in TwoColumns → Primary
 *
 */
interface TwoColumnsSliceTextWithChecklistStyle2Primary {
  /**
   * Icon Classname field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_classname: prismicT.KeyTextField;
  /**
   * Title field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *TwoColumns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Item Icon Classname field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.item_icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  item_icon_classname: prismicT.KeyTextField;
  /**
   * Is Revert field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_revert
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_revert: prismicT.BooleanField;
  /**
   * Image field in *TwoColumns → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * HTML Type field in *TwoColumns → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.html_type
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  html_type: prismicT.SelectField<
    "Singleflow" | "Animation" | "Form" | "Two Image1" | "Two Image2"
  >;
  /**
   * text1 field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.text1
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text1: prismicT.KeyTextField;
  /**
   * text2 field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.text2
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text2: prismicT.KeyTextField;
  /**
   * text3 field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.text3
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text3: prismicT.KeyTextField;
  /**
   * text4 field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.text4
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text4: prismicT.KeyTextField;
  /**
   * Is Background Light field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_background_light
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_background_light: prismicT.BooleanField;
}
/**
 * Item in TwoColumns → Items
 *
 */
export interface TwoColumnsSliceTextWithChecklistStyle2Item {
  /**
   * Title field in *TwoColumns → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
}
/**
 * Text with Checklist style 2 variation for TwoColumns Slice
 *
 * - **API ID**: `textWithChecklistStyle2`
 * - **Description**: `TwoColumns`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnsSliceTextWithChecklistStyle2 =
  prismicT.SharedSliceVariation<
    "textWithChecklistStyle2",
    Simplify<TwoColumnsSliceTextWithChecklistStyle2Primary>,
    Simplify<TwoColumnsSliceTextWithChecklistStyle2Item>
  >;
/**
 * Primary content in TwoColumns → Primary
 *
 */
interface TwoColumnsSliceTextAndFeaturesPrimary {
  /**
   * Icon Classname field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_classname: prismicT.KeyTextField;
  /**
   * Title field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Is Revert field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_revert
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_revert: prismicT.BooleanField;
  /**
   * Image field in *TwoColumns → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * HTML Type field in *TwoColumns → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.html_type
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  html_type: prismicT.SelectField<
    "Singleflow" | "Animation" | "Form" | "Two Image1" | "Two Image2"
  >;
  /**
   * Is Background Light field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_background_light
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_background_light: prismicT.BooleanField;
}
/**
 * Item in TwoColumns → Items
 *
 */
export interface TwoColumnsSliceTextAndFeaturesItem {
  /**
   * Icon Classname field in *TwoColumns → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.items[].icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_classname: prismicT.KeyTextField;
  /**
   * Title field in *TwoColumns → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *TwoColumns → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Text and Features variation for TwoColumns Slice
 *
 * - **API ID**: `textAndFeatures`
 * - **Description**: `TwoColumns`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnsSliceTextAndFeatures = prismicT.SharedSliceVariation<
  "textAndFeatures",
  Simplify<TwoColumnsSliceTextAndFeaturesPrimary>,
  Simplify<TwoColumnsSliceTextAndFeaturesItem>
>;
/**
 * Primary content in TwoColumns → Primary
 *
 */
interface TwoColumnsSliceTextWithStatisticsPrimary {
  /**
   * Icon Classname field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.icon_classname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_classname: prismicT.KeyTextField;
  /**
   * Title field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *TwoColumns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Is Revert field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_revert
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_revert: prismicT.BooleanField;
  /**
   * Image field in *TwoColumns → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * HTML Type field in *TwoColumns → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.html_type
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  html_type: prismicT.SelectField<
    "Singleflow" | "Animation" | "Form" | "Two Image1" | "Two Image2"
  >;
  /**
   * Is Background Light field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_background_light
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_background_light: prismicT.BooleanField;
}
/**
 * Item in TwoColumns → Items
 *
 */
export interface TwoColumnsSliceTextWithStatisticsItem {
  /**
   * Title Number field in *TwoColumns → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.items[].title_number
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  title_number: prismicT.NumberField;
  /**
   * Title Text field in *TwoColumns → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.items[].title_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_text: prismicT.KeyTextField;
  /**
   * Description field in *TwoColumns → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
}
/**
 * Text with Statistics variation for TwoColumns Slice
 *
 * - **API ID**: `textWithStatistics`
 * - **Description**: `TwoColumns`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnsSliceTextWithStatistics = prismicT.SharedSliceVariation<
  "textWithStatistics",
  Simplify<TwoColumnsSliceTextWithStatisticsPrimary>,
  Simplify<TwoColumnsSliceTextWithStatisticsItem>
>;
/**
 * Primary content in TwoColumns → Primary
 *
 */
interface TwoColumnsSliceTextWithAccordionsPrimary {
  /**
   * Title field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *TwoColumns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Is Revert field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_revert
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_revert: prismicT.BooleanField;
  /**
   * image field in *TwoColumns → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * HTML Type field in *TwoColumns → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.html_type
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  html_type: prismicT.SelectField<
    "Singleflow" | "Animation" | "Form" | "Two Image1" | "Two Image2"
  >;
  /**
   * text1 field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.text1
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text1: prismicT.KeyTextField;
  /**
   * text2 field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.text2
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text2: prismicT.KeyTextField;
  /**
   * text3 field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.text3
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text3: prismicT.KeyTextField;
  /**
   * text4 field in *TwoColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.primary.text4
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text4: prismicT.KeyTextField;
  /**
   * Is Background Light field in *TwoColumns → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_columns.primary.is_background_light
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_background_light: prismicT.BooleanField;
}
/**
 * Item in TwoColumns → Items
 *
 */
export interface TwoColumnsSliceTextWithAccordionsItem {
  /**
   * Title field in *TwoColumns → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Description field in *TwoColumns → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_columns.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Text With accordions variation for TwoColumns Slice
 *
 * - **API ID**: `textWithAccordions`
 * - **Description**: `TwoColumns`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnsSliceTextWithAccordions = prismicT.SharedSliceVariation<
  "textWithAccordions",
  Simplify<TwoColumnsSliceTextWithAccordionsPrimary>,
  Simplify<TwoColumnsSliceTextWithAccordionsItem>
>;
/**
 * Slice variation for *TwoColumns*
 *
 */
type TwoColumnsSliceVariation =
  | TwoColumnsSliceDefault
  | TwoColumnsSliceTextWithLogos
  | TwoColumnsSliceTextWithChecklistStyle1
  | TwoColumnsSliceTextWithChecklistStyle2
  | TwoColumnsSliceTextAndFeatures
  | TwoColumnsSliceTextWithStatistics
  | TwoColumnsSliceTextWithAccordions;
/**
 * TwoColumns Shared Slice
 *
 * - **API ID**: `two_columns`
 * - **Description**: `TwoColumns`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnsSlice = prismicT.SharedSlice<
  "two_columns",
  TwoColumnsSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      ArticleDocumentData,
      ArticleDocument,
      BlogDocumentData,
      BlogDocument,
      CookieDocumentData,
      CookieDocumentDataCardItem,
      CookieDocument,
      FooterDocumentData,
      FooterDocumentDataLinkListItem,
      FooterDocument,
      GdprDocumentData,
      GdprDocument,
      HeaderDocumentData,
      HeaderDocumentDataLinkListItem,
      HeaderDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      PricingDocumentData,
      PricingDocumentDataSlicesSlice,
      PricingDocument,
      PrivacyDocumentData,
      PrivacyDocument,
      AllDocumentTypes,
      BannerSliceDefaultPrimary,
      BannerSliceDefault,
      BannerSliceVariation,
      BannerSlice,
      ComparisonTablesSliceDefaultPrimary,
      ComparisonTablesSliceDefaultItem,
      ComparisonTablesSliceDefault,
      ComparisonTablesSliceVariation,
      ComparisonTablesSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceDefault,
      FaqSliceStyle1Primary,
      FaqSliceStyle1Item,
      FaqSliceStyle1,
      FaqSliceVariation,
      FaqSlice,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceDefaultItem,
      FeaturesSliceDefault,
      FeaturesSliceFunctionsPrimary,
      FeaturesSliceFunctionsItem,
      FeaturesSliceFunctions,
      FeaturesSliceVariation,
      FeaturesSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefault,
      HeroSliceStyle1Primary,
      HeroSliceStyle1Item,
      HeroSliceStyle1,
      HeroSliceStyle2Primary,
      HeroSliceStyle2Item,
      HeroSliceStyle2,
      HeroSliceStyle3Primary,
      HeroSliceStyle3Item,
      HeroSliceStyle3,
      HeroSliceStyle4Primary,
      HeroSliceStyle4Item,
      HeroSliceStyle4,
      HeroSliceVariation,
      HeroSlice,
      HighlightSliceDefaultPrimary,
      HighlightSliceDefaultItem,
      HighlightSliceDefault,
      HighlightSliceVariation,
      HighlightSlice,
      HighlightNormalSliceDefaultPrimary,
      HighlightNormalSliceDefault,
      HighlightNormalSliceVariation,
      HighlightNormalSlice,
      PricingSliceDefaultPrimary,
      PricingSliceDefaultItem,
      PricingSliceDefault,
      PricingSliceVariation,
      PricingSlice,
      ProcessSliceDefaultPrimary,
      ProcessSliceDefaultItem,
      ProcessSliceDefault,
      ProcessSliceVariation,
      ProcessSlice,
      ReveiwsSliceDefaultPrimary,
      ReveiwsSliceDefaultItem,
      ReveiwsSliceDefault,
      ReveiwsSliceStyle2Primary,
      ReveiwsSliceStyle2Item,
      ReveiwsSliceStyle2,
      ReveiwsSliceVariation,
      ReveiwsSlice,
      RewardSliceDefaultPrimary,
      RewardSliceDefault,
      RewardSliceVariation,
      RewardSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceDefault,
      TestimonialsSliceVariation,
      TestimonialsSlice,
      TwoColumnsSliceDefault,
      TwoColumnsSliceTextWithLogosPrimary,
      TwoColumnsSliceTextWithLogosItem,
      TwoColumnsSliceTextWithLogos,
      TwoColumnsSliceTextWithChecklistStyle1Primary,
      TwoColumnsSliceTextWithChecklistStyle1Item,
      TwoColumnsSliceTextWithChecklistStyle1,
      TwoColumnsSliceTextWithChecklistStyle2Primary,
      TwoColumnsSliceTextWithChecklistStyle2Item,
      TwoColumnsSliceTextWithChecklistStyle2,
      TwoColumnsSliceTextAndFeaturesPrimary,
      TwoColumnsSliceTextAndFeaturesItem,
      TwoColumnsSliceTextAndFeatures,
      TwoColumnsSliceTextWithStatisticsPrimary,
      TwoColumnsSliceTextWithStatisticsItem,
      TwoColumnsSliceTextWithStatistics,
      TwoColumnsSliceTextWithAccordionsPrimary,
      TwoColumnsSliceTextWithAccordionsItem,
      TwoColumnsSliceTextWithAccordions,
      TwoColumnsSliceVariation,
      TwoColumnsSlice,
    };
  }
}
