// Code generated by Slice Machine. DO NOT EDIT.

import Banner from "./Banner";
import ComparisonTables from "./ComparisonTables";
import Faq from "./Faq";
import Features from "./Features";
import Hero from "./Hero";
import Highlight from "./Highlight";
import HighlightNormal from "./HighlightNormal";
import Pricing from "./Pricing";
import Process from "./Process";
import Reveiws from "./Reveiws";
import Reward from "./Reward";
import Testimonials from "./Testimonials";
import TwoColumns from "./TwoColumns";

export {
  Banner,
  ComparisonTables,
  Faq,
  Features,
  Hero,
  Highlight,
  HighlightNormal,
  Pricing,
  Process,
  Reveiws,
  Reward,
  Testimonials,
  TwoColumns,
};

export const components = {
  banner: Banner,
  comparison_tables: ComparisonTables,
  faq: Faq,
  features: Features,
  hero: Hero,
  highlight: Highlight,
  highlight_normal: HighlightNormal,
  pricing: Pricing,
  process: Process,
  reveiws: Reveiws,
  reward: Reward,
  testimonials: Testimonials,
  two_columns: TwoColumns,
};
